---
- name: Converge
  hosts: all
  gather_facts: False
  vars:
    django_project_path: '/root'
    django_project_name: 'test'
    cron_tasks:
      - name: "test"
        minute: 55
        hour: 23
        weekday: "Mon,Thu"
        day: "*"
        month: "*"
        job: "/tmp/test.sh > /tmp/env"
    cron_vars:
      - name: MAILTO
        value: mail@example.com
  roles:
    - ansible-cron-role
